# Generated by Django 2.2 on 2023-01-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0002_farm_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='farm_base.State')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='farm_base.City'),
            preserve_default=False,
        ),
    ]
